name: dart_board_chat
description: Realtime Chat based on Firebase Firestore.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_firebase_database: 
    path: ../dart_board_firebase_database
  dart_board_authentication:    
  cupertino_icons: ^1.0.2
  intl:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_chat_feature
    iosBundleIdentifier: com.example.dartBoardChatFeature
