name: dart_board_spacex_ui
description: UI Layer for the Dart Board Space X demo
version: 1.0.3
homepage: https://dart-board.io
repository: https://github.com/ahammer/dart_board

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_board_core: ^0.9.14+1
  dart_board_space_scene: ^1.0.7
  dart_board_theme: ^0.9.4+4
  transparent_image: ^2.0.0
  url_launcher:  ^6.0.12
  dart_board_spacex_repository: ^1.0.4
  intl: ^0.17.0
  dart_board_locator: ^0.9.4+8
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.spacex_ui
    iosBundleIdentifier: com.example.spacexUi
