name: dart_board_log
description: An extension that brings interactive logging to a Dart Board app. Provides a toolbar and screen.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 0.9.2+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dart_board_core: ^0.9.13
  dart_board_locator: ^0.9.4+6
  logging: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.dart-board.log_extension
    iosBundleIdentifier: io.dart-board.log_extension
