name: dart_board_firebase_remote_config
description: Firebase Remote Config for Feature Management
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

# Configure firebase as per firebase documents
# E.g. configure the runner's with your keys for this to work

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.9
  dart_board_firebase_core: ^1.0.0+1
  firebase_remote_config:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_firebase_remote_config
    iosBundleIdentifier: com.example.dartBoardFirebaseRemoteConfig
