name: dart_board_minesweeper
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Redux for general global state
  redux: ^5.0.0 
  flutter_redux: ^0.8.2 
  redux_thunk: ^0.4.0 
  
  #For provider, for local component with more state  
  provider: ^5.0.0 

  #For immutable data types (Prevents bugs, makes Redux easier)
  build_runner: ^2.0.3 
  built_value: ^8.0.6 
  built_value_generator: ^8.0.6 

  #For Date formatting
  intl: ^0.17.0 

  #For stricter static analysis
  pedantic: ^1.11.0

  dart_board: 
    path: ../../dart_board
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true