name: dart_board_minesweeper
description: A minesweeper implementation ported to DartBoard.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board
version: 0.9.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Note: This feature was imported from another project 
  # and runs in a feature container.
  #
  # It is not an endorsement of proper Feature Design
  # More of a proof of concept to show dropping an existing 
  # app into a feature container. 

  flutter:
    sdk: flutter

  #Redux for general global state
  redux: ^5.0.0 
  flutter_redux: ^0.8.2 
  redux_thunk: ^0.4.0 
  
  #For provider, for local component with more state  
  provider: ^5.0.0 

  #For immutable data types (Prevents bugs, makes Redux easier)
  built_collection: ^5.0.0
  build_runner: ^2.0.3 
  built_value: ^8.0.6 
  built_value_generator: ^8.0.6 

  #For Date formatting
  intl: ^0.17.0 

  #For stricter static analysis
  pedantic: ^1.11.0

  dart_board_core: ^0.9.3    
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
