name: dart_board_splash
description: Helps you easily provide a splash screen to your application.
homepage: https://dart-board.io
version: 1.0.11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16
  dart_board_widgets: ^1.3.0
  dart_board_locator: ^0.9.5
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_splash
    iosBundleIdentifier: com.example.dartBoardSplash
