name: Flutter_Core_Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.2.2'
      - name: Switch to Core
        run: cd core/dart_board_core
      - name: Packages get
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash
        shell: bash
